"""Añadir origen, personalidad y visibilidad a Name

Revision ID: dc883c92b343
Revises: b1bce23f5698
Create Date: 2025-06-30 12:43:57.238161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc883c92b343'
down_revision = 'b1bce23f5698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_usuario', sa.String(), nullable=True),
    sa.Column('quiz_profile', sa.JSON(), nullable=False),
    sa.Column('nombres_entregados', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('fuente_ia', sa.Boolean(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_usuario', sa.String(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('tiempo_respuesta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('result_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_logs')
    op.drop_table('results')
    # ### end Alembic commands ###
